### ISSUE TITLE
R markdown document -- single model run at a location

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/AirFireModeling#20]
We will attempt to address the current request for model analysis output by creating a set of R markdown documents that we may later include in automated processing scripts or in a by-request web service.

The first markdown document will be `local_Rmd/model_receptor.Rmd` with a header something like this:

```
title: "Model Receptor Analysis"
output: html_document
params:
  model: "PNW-4km"
  modelRun: "2019111900"
  monitorID: NULL
  longitude: -120.25
  latitude: 45.5
  spatialDataDir: "~/Data/Spatial"
  modelDataDir: "~/Data/Bluesky"
```

This markdown document will contain headers, explanatory text and visual presentation but can hide most/all of the R code use to generate the plots.

Visualizations that should be included:

* Either a monitorID or lon, lat must be specified. If a monitor is specified, then lon, lat are extracted from the _ws_monitor_ object. 
* Timeseries plot at a location showing 1, 3, 5, 9, 16, 25 grid cells. These could be shown in one plot with different line styles or as separate plots or both. 
* **rasterVis** small multiples images (aka "static movie") for grid cells within ~100km of the "receptor" location. These can be shown as three separate 24-hr plots using 3x8 or 6x4 hourly images.
* If a `!is.na(monitorID)` then the monitor time series should be shown on top of any time series plots and the monitor location should be shown on top of any single timestep gird images.
